name: Rancher redeploy workload
description: An action for redeploying a Rancher workload
author: Gokhan Sari, perror
branding:
  icon: refresh-cw
  color: blue
runs:
  using: docker
  image: Dockerfile
